# Generated by Django 5.2.8 on 2025-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('rg', models.CharField(default='', max_length=14)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
