# Generated by Django 5.2.8 on 2025-11-24 14:42

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('CPF', models.CharField(default='', max_length=14)),
                ('RG', models.CharField(default='', max_length=14)),
                ('Data_Nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
                ('contato', models.CharField(max_length=16)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('Consulta_Realizada', models.CharField(choices=[('Sim', 'Sim'), ('Cancelou', 'Cancelou'), ('Faltou', 'Faltou'), ('Desistiu', 'Desistiu')], max_length=15)),
                ('Paciente_Trouxe_Exames', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=5)),
                ('Exames_Trazidos', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TC DE MAXILA - TIPO CONE BEAM', 'Tc De Maxila Tipo Cone Beam'), ('TC DE MANDÍBULA - TIPO CONE BEAM POR MEIO VIRTUAL OU POR E-MAIL', 'Tc De Mandibula Tipo Cone Beam Virtual'), ('TC CONE BEAM COM TRAÇADO PARA IMPLANTES', 'Tc Cone Beam Com Tracado Para Implantes'), ('RX DE FACE PO', 'Rx De Face Po'), ('RADIOGRAFIA OCLUSAL', 'Radiografia Oclusal'), ('RADIOGRAFIA PERIAPICAL', 'Radiografia Periapical'), ('RADIOGRAFIA PANORÂMICA SEM LAUDO', 'Radiografia Panoramica Sem Laudo'), ('RADIOGRAFIA PANORÂMICA COM LAUDO', 'Radiografia Panoramica Com Laudo'), ('RX PERFIL DE FACE', 'Rx Perfil De Face'), ('RX PA DE MANDÍBULA', 'Rx Pa De Mandibula'), ("RX WATER'S", 'Rx Waters'), ('RESSONÂNCIA MAGNÉTICA DE ATM', 'Ressonancia Magnetica De Atm'), ('RESSONÂNCIA MAGNÉTICA DE MAXILA', 'Ressonancia Magnetica De Maxila'), ('RESSONÂNCIA MAGNÉTICA DE MANDÍBULA', 'Ressonancia Magnetica De Mandibula'), ('ULTRASSONOGRAFIA DE GLÂNDULA SUBMANDIBULAR', 'Ultrassonografia De Glandula Submandibular'), ('ULTRASSONOGRAFIA DE GLÂNDULA PARÓTIDA', 'Ultrassonografia De Glandula Parotida'), ('TC DE SEIOS DA FACE', 'Tc De Seios Da Face'), ('TC DE FACE', 'Tc De Face'), ('TC DE FACE EM 3D', 'Tc De Face Em 3D'), ('TC DE MAXILA', 'Tc De Maxila'), ('TC DE MANDÍBULA', 'Tc De Mandibula'), ('TC DE MANDÍBULA - ATM', 'Tc De Mandibula Atm'), ('EXAMES SOLICITADOS POR OUTRO PROFISSIONAL', 'Exames Solicitados Por Outro Profissional'), ('EXAMES ORTOGNÁTICA - USP/MC NAMARA/ UNICAMP', 'Exames Ortognatica Usp Mcnamara Unicamp'), ('ULTRASSONOGRAFIA', 'Ultrassonografia')], max_length=100)),
                ('Laudos_dos_Exames_Trazidos', models.CharField(max_length=2000)),
                ('achados_clinicos_da_consulta', models.CharField(max_length=2000)),
                ('Conduta', models.CharField(max_length=2000)),
                ('Encaminhado_para_Outro_Profissional', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=5)),
                ('Profissional_Encaminhado', models.CharField(choices=[('NÃO', 'Nao'), ('ENDODONTIA', 'Endodontia'), ('FISIOTERAPIA', 'Fisioterapia'), ('CIRURGIÃO PLÁSTICO', 'Cirurgiao Plastico'), ('OTORRINO', 'Otorrino'), ('NEUROCLÍNICO', 'Neuroclinico'), ('NEUROCIRURGIA', 'Neurocirurgia'), ('PSICÓLOGO', 'Psicologo'), ('PSIQUIATRA', 'Psiquiatra'), ('NEFROLOGISTA', 'Nefrologista'), ('CARDIOLOGISTA', 'Cardiologista'), ('PROTESISTA', 'Protesista'), ('FONO', 'Fono'), ('ORTODONTISTA', 'Ortodontista'), ('DRA. SÂMYA CABRAL', 'Dra Samya Cabral'), ('DRA. MÔNICA TAIRA', 'Dra Monica Taira'), ('DRA. HOSANA BAIMA', 'Dra Hosana Baima'), ('DRA. GISELE GONZAGA', 'Dra Gisele Gonzaga'), ('DENTÍSTICA - ESTÉTICA', 'Dentistica Estetica'), ('DR. ANTÔNIO JORGE', 'Dr Antonio Jorge'), ('DR. MIGUEL LEDO', 'Dr Miguel Ledo')], max_length=70)),
                ('estimativa_diagnostico', models.CharField(max_length=2000)),
                ('exames_solicitados', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TC DE MAXILA - TIPO CONE BEAM', 'Tc De Maxila Tipo Cone Beam'), ('TC DE MANDÍBULA - TIPO CONE BEAM POR MEIO VIRTUAL OU POR E-MAIL', 'Tc De Mandibula Tipo Cone Beam Virtual'), ('TC CONE BEAM COM TRAÇADO PARA IMPLANTES', 'Tc Cone Beam Com Tracado Para Implantes'), ('RX DE FACE PO', 'Rx De Face Po'), ('RADIOGRAFIA OCLUSAL', 'Radiografia Oclusal'), ('RADIOGRAFIA PERIAPICAL', 'Radiografia Periapical'), ('RADIOGRAFIA PANORÂMICA SEM LAUDO', 'Radiografia Panoramica Sem Laudo'), ('RADIOGRAFIA PANORÂMICA COM LAUDO', 'Radiografia Panoramica Com Laudo'), ('RX PERFIL DE FACE', 'Rx Perfil De Face'), ('RX PA DE MANDÍBULA', 'Rx Pa De Mandibula'), ("RX WATER'S", 'Rx Waters'), ('RESSONÂNCIA MAGNÉTICA DE ATM', 'Ressonancia Magnetica De Atm'), ('RESSONÂNCIA MAGNÉTICA DE MAXILA', 'Ressonancia Magnetica De Maxila'), ('RESSONÂNCIA MAGNÉTICA DE MANDÍBULA', 'Ressonancia Magnetica De Mandibula'), ('ULTRASSONOGRAFIA DE GLÂNDULA SUBMANDIBULAR', 'Ultrassonografia De Glandula Submandibular'), ('ULTRASSONOGRAFIA DE GLÂNDULA PARÓTIDA', 'Ultrassonografia De Glandula Parotida'), ('TC DE SEIOS DA FACE', 'Tc De Seios Da Face'), ('TC DE FACE', 'Tc De Face'), ('TC DE FACE EM 3D', 'Tc De Face Em 3D'), ('TC DE MAXILA', 'Tc De Maxila'), ('TC DE MANDÍBULA', 'Tc De Mandibula'), ('TC DE MANDÍBULA - ATM', 'Tc De Mandibula Atm'), ('EXAMES SOLICITADOS POR OUTRO PROFISSIONAL', 'Exames Solicitados Por Outro Profissional'), ('EXAMES ORTOGNÁTICA - USP/MC NAMARA/ UNICAMP', 'Exames Ortognatica Usp Mcnamara Unicamp'), ('ULTRASSONOGRAFIA', 'Ultrassonografia')], max_length=100)),
                ('retorno_realizado', models.CharField(choices=[('Pendente', 'Pendente'), ('Sim', 'Sim'), ('Cancelou', 'Cancelou'), ('Faltou', 'Faltou')], default='Pendente', max_length=15)),
                ('Laudos_dos_Exames_solicitados', models.CharField(max_length=2000)),
                ('achados_clinicos_do_retorno', models.CharField(max_length=2000)),
                ('Encaminhado_para_Outro_Profissional_retorno', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=5)),
                ('Profissional_Encaminhado_retorno', models.CharField(choices=[('NÃO', 'Nao'), ('ENDODONTIA', 'Endodontia'), ('FISIOTERAPIA', 'Fisioterapia'), ('CIRURGIÃO PLÁSTICO', 'Cirurgiao Plastico'), ('OTORRINO', 'Otorrino'), ('NEUROCLÍNICO', 'Neuroclinico'), ('NEUROCIRURGIA', 'Neurocirurgia'), ('PSICÓLOGO', 'Psicologo'), ('PSIQUIATRA', 'Psiquiatra'), ('NEFROLOGISTA', 'Nefrologista'), ('CARDIOLOGISTA', 'Cardiologista'), ('PROTESISTA', 'Protesista'), ('FONO', 'Fono'), ('ORTODONTISTA', 'Ortodontista'), ('DRA. SÂMYA CABRAL', 'Dra Samya Cabral'), ('DRA. MÔNICA TAIRA', 'Dra Monica Taira'), ('DRA. HOSANA BAIMA', 'Dra Hosana Baima'), ('DRA. GISELE GONZAGA', 'Dra Gisele Gonzaga'), ('DENTÍSTICA - ESTÉTICA', 'Dentistica Estetica'), ('DR. ANTÔNIO JORGE', 'Dr Antonio Jorge'), ('DR. MIGUEL LEDO', 'Dr Miguel Ledo')], max_length=70)),
                ('confimacao_diagnostico', models.CharField(max_length=2000)),
                ('conduta_retorno', models.CharField(max_length=2000)),
                ('paciente_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('Data_do_Agendamento', models.DateField()),
                ('Tipo_da_Consulta', models.CharField(choices=[('Particular', 'Particular'), ('Convênio', 'Convenio')], max_length=15)),
                ('Qual_Plano', models.CharField(choices=[('Bradesco', 'Bradesco')], max_length=15, null=True)),
                ('Carteira_do_Plano', models.CharField(max_length=15, null=True)),
                ('Data_da_Consulta', models.DateField()),
                ('Valor_da_Consulta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Emitiu_Nota_Fiscal', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=5)),
                ('Queixa_do_Paciente', models.CharField(max_length=2000)),
                ('data_do_retorno', models.DateField()),
                ('paciente_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clinica.paciente')),
            ],
        ),
    ]
