<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-11 16:21
=======
# Generated by Django 5.2.8 on 2025-11-11 21:32
>>>>>>> 5d10c62c16aac5a2d5a1edd09da885006a1c9959

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_paciente', models.CharField(default='', max_length=100)),
                ('cpf_paciente', models.CharField(default='', max_length=14)),
                ('rg_paciente', models.CharField(default='', max_length=14)),
                ('data_nascimento_paciente', models.DateField()),
<<<<<<< HEAD
                ('sexo_paciente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
=======
                ('sexo_paciente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1)),
>>>>>>> 5d10c62c16aac5a2d5a1edd09da885006a1c9959
                ('numero_paciente', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro_endereco', models.CharField(max_length=100)),
                ('numero_endereco', models.IntegerField()),
                ('bairro_endereco', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('cep_endereco', models.CharField(max_length=9)),
=======
                ('cep_endereco', models.CharField(max_length=100)),
>>>>>>> 5d10c62c16aac5a2d5a1edd09da885006a1c9959
                ('cidade_endereco', models.CharField(max_length=100)),
                ('estado_endereco', models.CharField(max_length=2)),
                ('fk_id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
    ]
